services:
  - type: web
    name: pullup-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      PYTHONPATH=/opt/render/project/src/backend gunicorn --chdir /opt/render/project/src/backend pullup.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MAKE_WEBHOOK_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
